version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tech-library-postgres
    environment:
      POSTGRES_USER: techlib
      POSTGRES_PASSWORD: techlib123
      POSTGRES_DB: tech_library_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U techlib']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tech-library-network

  redis:
    image: redis:7-alpine
    container_name: tech-library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tech-library-network

volumes:
  postgres_data:
  redis_data:

networks:
  tech-library-network:
    driver: bridge
